package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"golang_password_validator_api/graph/model"
)

// Password is the resolver for the password field.
func (r *queryResolver) Password(ctx context.Context) ([]*model.Password, error) {
	fmt.Println(&r)
	panic(fmt.Errorf("not implemented: Password - password"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
