// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Password struct {
	Password string `json:"password"`
}

type RuleInput struct {
	Rule  string `json:"rule"`
	Value int    `json:"value"`
}

type ValidatorPasswordInput struct {
	Password string       `json:"password"`
	Rules    []*RuleInput `json:"rules"`
}
